apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: '../android-config.gradle'

android {
    namespace 'com.farsitel.bazaar.core'

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
kotlin {
    jvmToolchain(17)
}

ext {
    package_id = 'Core'
    artifact_id = 'core'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$libraryVersions.kotlin"
    implementation "androidx.appcompat:appcompat:$libraryVersions.appcompat"
    implementation "androidx.core:core-ktx:$libraryVersions.androidx"
}

apply from: "$rootDir/jitpack/publish.gradle"