apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: '../android-config.gradle'

android {
    namespace 'com.farsitel.bazaar.auth.legacy'
}

ext {
    package_id = 'Auth-Legacy'
    artifact_id = 'auth-legacy'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    api project(":core")
}

apply from: "$rootDir/jitpack/publish.gradle"